---
#
#
# docker-compose up --build
#
version: '3.8'

services:
  jenkins:
    build:
      context: .
    container_name: Jenkins
    hostname: jenkins
    ports:
      - 80:8081
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./conf:/var/jenkins_config/
      - ./ansible:/home/ansible/
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_config/jenkins.yaml
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID:?Please configure JENKINS_ADMIN_ID in the .env file}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:?Please configure JENKINS_ADMIN_PASSWORD in the .env file}
      - JENKINS_OPTS="--httpPort=8081"